### ISSUE TITLE
no value.properties?

### ISSUE THREAD

**Issue by design365** [arunkumar9t2/lynket-browser#100]
is the code finished? 
when i download android studio show me :

Error:(30, 1) A problem occurred evaluating project ':app'.
> /.........................../project/lynket-browser/android-app/values.properties (No such file or directory)

why?

**Comment by arunkumar9t2** [comment]
Please create a values.properties file in /android-app/values.properties. It usually contains PLAY_LICENSE_KEY and FABRIC_KEY. Create a project on fabric and add the api key here. PLAY_LICENSE_KEY is optional.

Reference : https://fabric.io/kits/android/crashlytics/install

LMK if that works.
