### ISSUE TITLE
Off-by-one error in Web Heads mode

### ISSUE THREAD

**Issue by dgw** [arunkumar9t2/lynket-browser#101]
Lynket on my Razer Phone (Android 8.1, Lynket version 2.0.1) somehow got into an off-by-one state where if one Web Head was open, it displayed "0" on the badge.

I have Web Heads set to close once clicked. When I clicked the second-to-last Web Head (there should still be one more to open after I finished reading that page), the last one disappeared.

Force closing Lynket seems to have resolved the issue, and I can't find any way to generate a logcat. It started probably a couple days ago now, so chances are the genesis of the issue wouldn't be in the log anyway… But if there is a way to make a log, do let me know so I can generate one if this happens again.

**Comment by arunkumar9t2** [comment]
Hey thanks for letting me know! I have planned a huge rework in webheads and will definitely address this.

**Comment by dgw** [comment]
Just encountered this again in Lynket version 2.0.2. Same device & OS version. See the "0" in this screenshot:

![](https://i.imgur.com/rjPedNB.png)

**Comment by dgw** [comment]
I haven't seen this happen again, in nearly 3 years. It's probably time to close this until/unless it can be reproduced again.

**Comment by arunkumar9t2** [comment]
Thanks for following through. Progress has been slow on maintenance update although I still intend to work on improvements when time permits.

**Comment by dgw** [comment]
It's not enough to reopen this, IMO, but I had something like this happen again today. Android 12, ASUS ROG Phone 3, Lynket 2.1.3

I thought I'd opened all of my bubbles, including the "0" one, but on multiple occasions Lynket still displayed a "Web Heads open" notification until I tapped it.

Eventually, when it became clear something was off, force-stopping Lynket seems to have fixed it. Still an odd little edge case, but if it only happens a few times a decade I can live with it 😂
