### ISSUE TITLE
For the "Copy All" or "Share All" use `comma newline` instead of just `comma` to make it easier for humans to read

### ISSUE THREAD

**Issue by dragon788** [arunkumar9t2/lynket-browser#109]
When sharing to other apps like Hangouts/etc, it would be easier to read if the links were separated by newlines in addition to commas to help with the readability.

**Comment by SubhrajyotiSen** [comment]
What would be the new 'Choose share method' dialog option string?
Right now the option is "Comma separated"

**Comment by arunkumar9t2** [comment]
I think we can add another option with text `Separated by new line`

**Comment by SubhrajyotiSen** [comment]
Can I pick up this issue?

**Comment by arunkumar9t2** [comment]
Yes, please! Very much appreciated. Thank you.
