### ISSUE TITLE
[Feature request] Add other search engines

### ISSUE THREAD

**Issue by neekless** [arunkumar9t2/lynket-browser#113]
Selecting some text on a website and tapping 'Open/search with Lynket' opens a Google search of the selected text. It will be good if the search can be done using other engines, e.g. duckduckgo. Not sure how easy it is to implement this but I hope it's possible.

**Comment by arunkumar9t2** [comment]
Related #28 

This will be on priority for next version.

**Comment by neekless** [comment]
Oops, should have searched for this. I will close this.
