### ISSUE TITLE
Default search engine on selected text

### ISSUE THREAD

**Issue by neekless** [arunkumar9t2/lynket-browser#124]
Default search engine was changed to duckduckgo and typing something into lynket's search bar searches with the correct search provider, as expected.

But when selecting text and tapping 'Open/Search with Lynket', it searches with Google. 
![Screenshot_20190914-222800](https://user-images.githubusercontent.com/22426822/64909483-594f9080-d6fc-11e9-8d91-cc3e890464e0.jpg)

**Comment by arunkumar9t2** [comment]
Thanks for letting me know. I came across this too. I will fix this in a
hotfix update.
