### ISSUE TITLE
(Add)  puffin browser 

### ISSUE THREAD

**Issue by 3xploiton3** [arunkumar9t2/lynket-browser#128]
Fastest browser on average benchmark

https://play.google.com/store/apps/details?id=com.cloudmosa.puffinFree

**Comment by arunkumar9t2** [comment]
Hi, Lynket does need to specifically add browsers and it automatically shows the browser in the list if it supports custom tab protocol. In this case, Puffin does not. It would be better to send them feedback to support custom tab protocol. Once they do, Lynket would automatically show it as supported without any update.
