### ISSUE TITLE
Bottom bar is shown for Chrome rendering, but not for Firefox or F. Focus

### ISSUE THREAD

**Issue by alainsr** [arunkumar9t2/lynket-browser#136]
I like the bottom bar. But it suddenly stopped showing. I can't recall when/what exactly changed it, but I can say it works properly it I set Chrome as the rendering browser, and it simply isn't there anymore when I switch rendering to either Firefox or Firefox Focus.

**Comment by arunkumar9t2** [comment]
Unfortunately Firefox and Firefox Focus does not implement the bottom bar API in Google's custom tab spec. Lynket already sends the required information to all browsers for rendering bottom bar but it remains a choice for those browser whether to use it or not. I am closing this for now, please feel free to reopen should you have any concerns
