### ISSUE TITLE
"release" build without Crashlytics?

### ISSUE THREAD

**Issue by IzzySoft** [arunkumar9t2/lynket-browser#140]
Would you consider a tracking-free release-type flavor (i.e. buildType "release" with `ext.enableCrashlytics = false`) to make us tin-foils happy – and maybe even bring your app to F-Droid? Even just an `*-noanalytics.apk` next to the current APK at releases would be much appreciated.

Thanks in advance!

**Comment by IzzySoft** [comment]
PS: this probably can be considered a first step towards solving #7 (sorry, re-discovered the latter only after I already had opened this one here).

**Comment by arunkumar9t2** [comment]
Hi, I am still considering launching on F-Droid, I will try to allocate some time for this. I prefer to track this in #7 so closing this. Please feel free to open if you have any other concern.

**Comment by IzzySoft** [comment]
Totally fine, thanks!
