### ISSUE TITLE
Microcopy change when sharing 

### ISSUE THREAD

**Issue by iprithvitharun** [arunkumar9t2/lynket-browser#144]
![Screenshot_2020-02-04-19-54-19-167_android](https://user-images.githubusercontent.com/58725708/73753278-76a6f900-4788-11ea-8f96-f23a66390f23.jpg)

URL is an acronym and it should be capitalized. 

Also, the microcopy isn't leading the users to do the next action.

**Comment by iprithvitharun** [comment]
@arunkumar9t2 I can work on this.

**Comment by arunkumar9t2** [comment]
Yes thank you, please submit a PR. 

Also  

> Also, the microcopy isn't leading the users to do the next action.

what do you mean by this?

**Comment by iprithvitharun** [comment]
@arunkumar9t2 I meant that "..." feels incomplete. It gives the impression that there is much to it than just sharing. 

I'll send a Pull Request for this soon. Working on different copies and testing it with my friends now.
