### ISSUE TITLE
Open link from Youtube

### ISSUE THREAD

**Issue by Kimphunh** [arunkumar9t2/lynket-browser#169]
Some apps like youtube don't use slide over so that Lynket not on the open list
But some apps that ain't browser are on the open list like Mixplorer?office reader?
Hope you fix it soon🐧💐

**Comment by arunkumar9t2** [comment]
This will be fixed by https://github.com/arunkumar9t2/lynket-browser/issues/74

**Comment by Kimphunh** [comment]
but lynket's bubble is old and broken on android 11.it has become a main feature and not on developer mode anymore.so you need to update lynket
